/*
SELECT 
    b.TITLE, 
    b.BOARD_ID, 
    r.REPLY_ID, 
    r.WRITER_ID, 
    r.CONTENTS, 
    DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r 
    ON r.BOARD_ID = b.BOARD_ID
WHERE r.CREATED_DATE >= '2022-10-01' 
  AND r.CREATED_DATE < '2022-11-01'
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC; */

SELECT a.TITLE
     , a.BOARD_ID
     , b.REPLY_ID
     , b.WRITER_ID
     , b.CONTENTS
     , DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD a JOIN USED_GOODS_REPLY b ON a.BOARD_ID = b.BOARD_ID
WHERE DATE_FORMAT(a.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY b.CREATED_DATE, a.TITLE